### PR TITLE
RabbitMQ Metrics Script

### PR DESCRIPTION
**Pull request by nickethier**
This script will call the rabbitmq management api for various statistics. I added the restler http client lib to the deps for it. 

Its configured in the conf file as such:

``` javascript
{
  "username": "guest",
  "password": "guest",
  "host": "http://rabbit.mycompany.com",
  "port": 55672
}
```

### CODE REVIEW

**Comment by coredump** [comment]
Where goes this configuration? On hoardd main? Take a look on https://github.com/coredump/hoardd/blob/master/scripts-available/mysql.coffee to see how I did with the mysql one.

**Comment by nickethier** [comment]
Ah I see, let me add another commit real quick.

**Comment by nickethier** [comment]
Alright, moved the configuration to a rabbitmq.json file in the scripts directory. I updated the pull request to reflect the configuration change.

**Comment by coredump** [comment]
ok this seems ok. I don't have my grafite setup here now but until the end of the week I will test it. Thanks!

**Pull request merged**
