### PR TITLE
CPU utilization via the /proc/stat file

### PR DESCRIPTION
**Pull request by nickethier**
I wanted to move to HoardD from collectd. The only thing stopping me was the ability to get detailed cpu utilization on a per cpu basis. So I put on my nodejs hat and wrote this script. No configuration needed.

It will show all usage for the various kernel defined operations. I think as of the latest kernel there are 10 of them: user, nice, system, idle, iowait, irq, softirq, steal, guest, and guest_nice. This script should work for earlier kernels that may only have 8 or 9 of the fields.

### CODE REVIEW

**Comment by coredump** [comment]
I will have to give a little research and test that.

**Comment by nickethier** [comment]
I tested the cpu with the counter. I found the rate of the average idle among all my cpus, scaled it and compaired it with what vmstat said. [This may work](http://twitpic.com/9ix26n)

**Comment by nickethier** [comment]
There seems to be alot of problems that arise when you try to find rates in this way. For example if I want to look at long term trending, my scaling factor is going to be much different than if I were zoomed in at a 10 min interval. 

Is there some global namespace that I can store the previous read values into. Then on future reads I can find the percentage, send it off and update the old values. This would let me achieve what I was doing before, without reading twice  in one go.

**Comment by nickethier** [comment]
Nevermind, I figured it out!

Something like this works for me
scale(divideSeries(derivative(hoard.[host].cpu.0.*),derivative(sumSeries(hoard.[host].cpu.0.*))),100)

Now I'll push a commit to fix it.

**Comment by coredump** [comment]
There must be a easier way to get that status. Closing it for now so I can investigate alternatives.

**Pull request closed without merging**
